# @package model
defaults:
  - /model/segmentation/default

model:
  conv_type: "DENSE"
  backbone:
    _target_: torch_points3d.applications.pointnet2.PointNet2
    config:
      down_conv:
        module_name: PointNetMSGDown
        npoint: [1024, 256, 64, 16]
        radii: [[0.05, 0.1], [0.1, 0.2], [0.2, 0.4], [0.4, 0.8]]
        nsamples: [[16, 32], [16, 32], [16, 32], [16, 32]]
        down_conv_nn:
            [
                [[FEAT+3, 16, 16, 32], [FEAT+3, 32, 32, 64]],
                [[32 + 64+3, 64, 64, 128], [32 + 64+3, 64, 96, 128]],
                [
                    [128 + 128+3, 128, 196, 256],
                    [128 + 128+3, 128, 196, 256],
                ],
                [
                    [256 + 256+3, 256, 256, 512],
                    [256 + 256+3, 256, 384, 512],
                ],
            ]
      up_conv:
        module_name: DenseFPModule
        up_conv_nn:
            [
                [512 + 512 + 256 + 256, 512, 512],
                [512 + 128 + 128, 512, 512],
                [512 + 64 + 32, 256, 256],
                [256 + FEAT, 128, 128],
            ]
        skip: True
      mlp_cls:
        nn: [128, 128]
        dropout: 0.5
