exclude: 'benchmark|conf|data|docs|outputs'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=15000]
      - id: check-yaml

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args:
          [
            '--in-place',
            '--remove-unused-variable',
            '--ignore-init-module-imports',
            '--imports=torch,torch_geometric,torch_scatter,torch_cluster,numpy,sklearn,scipy,torch_sparse,torch_points_kernels',
          ]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: '.ipynb'

  # - repo: local
  #   hooks:
  #     - id: requirements.txt
  #       name: Generate requirements.txt
  #       entry: poetry export
  #       args:
  #         [
  #           '-f',
  #           'requirements.txt',
  #           '-o',
  #           'requirements.txt',
  #           '--without-hashes',
  #         ]
  #       pass_filenames: false
  #       language: system
  #       files: 'poetry.lock'
