defaults: # loads default configs
  - dataset: ???
  - model: ???
  - training: default
  - trainer: default

experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
log: False
ignore_warnings: True # todo: check warnings before release
pretty_print: True