# @package model
defaults:
  - /model/default

model:
  _recursive_: false
  _target_: torch_points3d.models.segmentation.base_model.SegmentationBaseModel
  num_classes: ${dataset.cfg.num_classes}

  backbone:
    input_nc: ${dataset.cfg.feature_dimension}
    architecture: unet